name: docs-preview-cleanup
on:
  pull_request_target:
    branches: [main]
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@df6069cc072a544dba23f19b363d2767d234cdc2 # v1
